@host = http://localhost:5277

GET {{host}}/questions
Accept: application/json

####

POST {{host}}/
Content-Type: application/json

{
  "text": "What is the capital of France?"
}

####

DELETE {{host}}/1

####


PUT {{host}}/2
Content-Type: application/json

{
  "text": "What is the capital of England?"
}

###

GET {{host}}/quizzes
Accept: application/json

####

POST {{host}}/quizzes
Content-Type: application/json

{
  "title": "Easy quiz!"
}

####

DELETE {{host}}/quizzes/1

####


PUT {{host}}/1
Content-Type: application/json

{
  "title": "Hard quiz!?"
}