@host = http://localhost:5277

GET {{host}}/questions
Accept: application/json

####

GET {{host}}/questions/1
Accept: application/json

###

POST {{host}}/questions
Content-Type: application/json

{
  "text": "What is the capital of France?",
  "OptionA": "London",
  "OptionB": "Dublin",
  "OptionC": "Paris",
  "OptionD": "Mobile",
  "CorrectOption": "C"
}

####

DELETE {{host}}/questions/1

####


PUT {{host}}/questions/1
Content-Type: application/json

{
  "text": "What is the capital of Alabama?",
  "OptionA": "London",
  "OptionB": "Mobile",
  "OptionC": "Montgomery",
  "OptionD": "Birmingham",
  "CorrectOption": "D"
}

###

GET {{host}}/quizzes
Accept: application/json

####

POST {{host}}/quizzes
Content-Type: application/json

{
  "title": "Easy quiz!"
}

####

DELETE {{host}}/quizzes/1

####


PUT {{host}}/1
Content-Type: application/json

{
  "title": "Hard quiz!?"
}

###

GET {{host}}/games
Accept: application/json

####

POST {{host}}/games
Content-Type: application/json

{
  "GameCode": "15",
  "Status": "Beginning"
}

####

DELETE {{host}}/games/1

####


PUT {{host}}/games/1
Content-Type: application/json

{
  "GameCode": "999",
  "Status": "Complete"
}